### ISSUE TITLE
Function to get right ascension, decline, and distance?

### ISSUE THREAD

**Issue by jakewilliami** [JuliaAstro/JPLEphemeris.jl#20]
Is there functionality (possibly using [AstroLib](https://juliaastro.github.io/AstroLib.jl/stable/ref.html)) to get the right ascension, decline, and distance of a planet with respect to earth?

**Comment by helgee** [comment]
There is no one-stop solution AFAIK but you should be able to piece something together with the tools provided by the ecosystem.

What coordinate frame do you want to use? Topocentric, i.e. RA and declination of the planets for some place on Earth? Or w.r.t. to the ecliptic or equatorial plane?

**Comment by jakewilliami** [comment]
The former I believe (Topocentric).  To be honest, my knowledge of this is limited.  I am trying to recreate a Python script I made a while back:
```python
from skyfield.api import load
import datetime

planets = load('de421.bsp')
earth, mercury = planets['earth'], planets['mercury']
ts = load.timescale()

ra, dec, distance = earth.at(ts.now()).observe(mercury)astrometric1.radec()

return ra
```
I'm just not exactly sure how to go about this using Julia.

**Comment by bgodard** [comment]
What you are showing here is not topocentric: topocentric means azimuth, elevation (above local horizon) for an observer.
If you want RA, DEC from the center of the Earth, you just get the vector:
```
position(spk, myplanet, jd) - position(spk, "earth", jd)
```
and convert it to spherical coordinates:
r * [  cos(ra) * cos(dec) , sin(ra) * cos(dec), sin(dec)  ]

But depending on your application you may also want to correct for light time, stellar aberration.

**Comment by jakewilliami** [comment]
Ah, I didn't know this.  Thank you @bgodard.  I have tried using `position` with this code
```julia
julia> using AstroLib, JPLEphemeris, Dates

julia> spk = SPK("de430.bsp")
SPK(DE-0430LE-0430)

julia> t1 = Dates.datetime2julian.(Dates.now())
2.4590243628225345e6
```
but I get the error
```julia
julia> position(spk, "earth", t1)
ERROR: MethodError: no method matching position(::SPK, ::String, ::Float64)
Closest candidates are:
  position(::AstroBase.Ephemerides.AbstractEphemeris, ::AstroTime.Epochs.Epoch, ::CelestialBody; kwargs...) at /Users/jakeireland/.julia/packages/AstroBase/LxXo1/src/Ephemerides/abstract.jl:84
  position(::AstroBase.Ephemerides.AbstractEphemeris, ::AstroTime.Epochs.Epoch, ::CelestialBody, ::CelestialBody; kwargs...) at /Users/jakeireland/.julia/packages/AstroBase/LxXo1/src/Ephemerides/abstract.jl:76
Stacktrace:
 [1] top-level scope at REPL[7]:1
```

**Comment by helgee** [comment]
The package is in bad shape right now. You might want to try [CALCEPH.jl](https://github.com/JuliaAstro/CALCEPH.jl) instead.

**Comment by jakewilliami** [comment]
Thanks for the suggestion @helgee!  So it [looks like](https://github.com/JuliaAstro/CALCEPH.jl/blob/master/docs/src/tutorial.md#computing-positions-and-velocities) I can just use (going off @bgodard's help)
```
compute(eph, jd1, jd2, naifId.id[:mercury], naifId.id[:earth])
```
to get the same result...right?

**Comment by bgodard** [comment]
```julia
compute(eph, jd1, jd2, naifId.id[:mercury], naifId.id[:earth], useNaifId+unitKM+unitSec,0)
```
You need to specify useNaifId and units. The 0 at the end is to get position only.

Note that ephemerides are generally given in ICRF reference axes which is the usual celestial reference for RA, DEC, but it may depend slightly on the application and depending on what your accuracy is you may care or not. If you tell us what is your application for, we can let you know if you need to apply other corrections.

**Comment by jakewilliami** [comment]
@bgodard I thought the last two parameters were optional?  Either way, I don't think `mercury` is supported here:
```
CALCEPH ERROR : Target object 199 is not supported.
ERROR: LoadError: CALCEPHException("Unable to compute ephemeris")
```

**Comment by bgodard** [comment]
Last two parameters are optional but without them:
* no possible use of NAIF Identifiers: you have to use the limited CALCEPH internal identification scheme. 
* no selection of output units
* default output of position + velocity (vector of 6 elements): you cannot get position ONLY.

The bodies which are supported depends on the ephemerides file you load.
I do not know which ephemerides file you are using but most planetary ephemerides usually contain only Earth, Moon, Sun and the barycenter of the planet-moons systems:
For most purpose the barycenter of the planet-moons is close enough to the planet. Because Mercury has no Moons its barycenter is identical.

So you might want to use identifier 1  or  naifId.id[:mercury_barycenter].

**Comment by jakewilliami** [comment]
Oh, I see.  Do you know if CALCEPH supports reading de430.bsp (as JPLEphemeris does)?  The ephemerides file which I am loading is inpop13c_TDB_m100_p100_tt.dat, which is the one on their README.

**Comment by helgee** [comment]
> Do you know if CALCEPH supports reading de430.bsp (as JPLEphemeris does)?

It does 👍

**Comment by bgodard** [comment]
de430.bsp should work fine but I expect it jas the same bodies as INPOP13C.

**Comment by jakewilliami** [comment]
Okay, thank you both very much.  I am sorry for my ignorance regarding all of this.  The current state of the conversation is far from the original "issue", so I suspect this should be closed.  However...I am still having issues.  Is one of you available for email communication while I get this working correctly?  Or perhaps there is a different, more appropriate place to ask these questions?

**Comment by helgee** [comment]
There is an `astronomy` channel on the Julia Slack where you can ask quick questions or you could start a thread on the Julia Discourse for more in-depth questions (https://discourse.julialang.org/c/domain/astro/32).

**Comment by jakewilliami** [comment]
Excellent, thank you both so much!
